[
  {
    restaurantName: "Taco Bell",
    type: "Fast Food Restaurants",
    websites: "http://www.tacobell.com",
    businessAddress: "7915 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Taco Bell",
    type: "Fast Food Restaurant and Mexican Restaurant",
    websites: "http://www.tacobell.com",
    businessAddress: "8270 N Cortaro Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Taco Bell",
    type: "Fast Food",
    websites: "http://www.tacobell.com",
    businessAddress: "495 E Wetmore Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Taco Bell",
    type: "Fast Food Restaurants",
    websites: "https://locations.tacobell.com",
    businessAddress: "4951 S Campbell Ave Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Taco Bell",
    type: "Fast Food Restaurant",
    websites: "http://www.tacobell.com",
    businessAddress: "1111 S Wilmot Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Taco Bell",
    type: "Fast Food Restaurants",
    websites: "http://www.tacobell.com",
    businessAddress: "1111 S Wilmot Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Taco Bell",
    type: "Fast Food Restaurant",
    websites: "http://www.tacobell.com",
    businessAddress: "3455 E Grant Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Burger King",
    type: "Fast Food Restaurant",
    websites: "http://bk.com,http://www.bk.com",
    businessAddress: "10615 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Wienerschnitzel",
    type: "Fast Food Restaurant",
    websites: "http://www.wienerschnitzel.com",
    businessAddress: "5765 E Broadway Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Arby's",
    type: "Fast Food Restaurants",
    websites: "http://www.arbys.com",
    businessAddress: "4299 W Ina Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Arby's",
    type: "Fast Food",
    websites: "http://www.arbys.com",
    businessAddress: "1530 W Valencia Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Arby's",
    type: "Fast Food Restaurant",
    websites: "http://www.arbys.com",
    businessAddress: "1530 W Valencia Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Arby's",
    type: "Fast Food Restaurant",
    websites: "http://www.arbys.com",
    businessAddress: "7285 E 22nd St Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "McDonald's",
    type: "Fast Food Restaurants",
    websites: "http://mcdonalds.com",
    businessAddress: "9490 E Golf Links Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "McDonald's",
    type: "Fast Food Restaurants",
    websites: "http://mcdonalds.com",
    businessAddress: "3315 N Swan Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "McDonald's",
    type: "Fast Food",
    websites: "http://mcdonalds.com",
    businessAddress: "3856 E Speedway Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "McDonald's",
    type: "Fast Food",
    websites:
      "http://mcdonalds.com,http://www.mcdonalds.com/?cid=RF:YXT_FM:TP::Yext:Referral",
    businessAddress: "3800 W Linda Vista Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "McDonald's",
    type: "Fast Food Restaurants",
    websites: "http://mcdonalds.com",
    businessAddress: "2250 W Ironwood Hill Dr Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "McDonald's",
    type: "Fast Food Restaurants",
    websites: "http://mcdonalds.com",
    businessAddress: "1711 E Speedway Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Panda Express",
    type: "Fast Food Restaurants",
    websites: "http://www.pandaexpress.com",
    businessAddress: "6370 E Golf Links Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Cousin's Subs",
    type: "Fast Food Restaurants",
    websites: "http://www.cousinssubs.com",
    businessAddress: "7401 N La Cholla Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Subway",
    type: "Fast Food Restaurants",
    websites: "http://www.subway.com",
    businessAddress: "6878 E Sunrise Dr Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Carl's Jr.",
    type: "Burger Joint, Fast Food Restaurant, and American Restaurant",
    websites: "http://carlsjr.com,http://www.carlsjr.com",
    businessAddress: "10535 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Jack in the Box",
    type: "Burger Joint, Fried Chicken Joint, and Fast Food Restaurant",
    websites: "http://www.jackinthebox.com",
    businessAddress: "3121 N Campbell Ave Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Jack in the Box",
    type: "Fast Food Restaurant",
    websites: "http://www.jackinthebox.com/locations/1150",
    businessAddress: "7031 E Tanque Verde Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Jack in the Box",
    type: "Fast Food Restaurants",
    websites: "http://www.jackinthebox.com",
    businessAddress: "8665 E Broadway Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Jack in the Box",
    type: "Fast Food Restaurant",
    websites: "http://www.jackinthebox.com",
    businessAddress: "4450 N 1st Ave Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Domino's Pizza",
    type: "Fast Food Restaurants",
    websites: "https://www.dominos.com",
    businessAddress: "1620 S Craycroft Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Burger King",
    type: "Fast Food Restaurants",
    websites: "https://locations.bk.com",
    businessAddress: "8702 E Broadway Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "KFC",
    type: "Fast Food Restaurant",
    websites: "http://kfc.com,http://www.kfc.com",
    businessAddress: "7901 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Wendy's",
    type: "Fast Food Restaurant and Burger Joint",
    websites: "http://wendys.com,http://www.wendys.com",
    businessAddress: "7675 N La Cholla Blvd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Burger King",
    type: "Fast Food Restaurant",
    websites: "http://bk.com",
    businessAddress: "2520 E Valencia Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "SONIC Drive In",
    type: "Fast Food Restaurants",
    websites: "http://sonicdrivein.com",
    businessAddress: "3255 W Orange Grove Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Eegee's",
    type: "Fast Food Restaurant",
    websites: "http://eegees.com,http://www.eegees.com",
    businessAddress: "3872 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Eegee's",
    type: "Sandwich Place, Fast Food Restaurant, and American Restaurant Amphi",
    websites: "http://eegees.com,http://www.eegees.com",
    businessAddress: "3872 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "McDonald's",
    type: "Fast Food",
    websites: "http://mcdonalds.com",
    businessAddress: "292 W McGee Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Jack in the Box",
    type: "Fast Food Restaurant",
    websites: "http://www.jackinthebox.com/locations/1571",
    businessAddress: "9530 E 22nd St Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Arby's",
    type: "Fast Food Restaurant",
    websites: "http://www.arbys.com",
    businessAddress: "16338 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Jimmy John's",
    type: "Sandwich Place and Fast Food Restaurant",
    websites: "http://www.jimmyjohns.com,http://jimmyjohns.com",
    businessAddress: "4356 N Oracle Rd Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Burger King",
    type: "Fast Food Restaurant",
    websites: "http://www.bk.com",
    businessAddress: "3915 W Costco Dr Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
  {
    restaurantName: "Domino's Pizza",
    type: "Fast Food Restaurants",
    websites: "https://www.dominos.com",
    businessAddress: "6875 E Sunrise Dr Tucson",
    faraway: "10 mil",
    description: "this is mini descrip",
    phone: 998888,
    email: "busienes@gmail.com",
    deliveryTime: 20,
    collectTime: 10,
    photo:
      "https://res.cloudinary.com/dugdmyq5b/image/upload/v1650923700/_profile116266fefa6ef520926042fd13.jpg",
  },
];
